linters:
  # Default linters enabled
  # See: https://golangci-lint.run/usage/linters/#enabled-by-default-linters

  # Additional linters enabled
  enable:
    - durationcheck
    - exportloopref
    - godot
    - gofmt
    - makezero
    - misspell
    - nilerr
    - predeclared
#    - tenv # TODO: Enable when upgrading Go 1.16 to 1.17
    - unconvert
    - unparam
