name: Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    name: Release
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check if any changes since last release
        id: check
        run: |
          git fetch --tags
          TAG=$(git tag --points-at HEAD)
          if [ -z "$TAG" ]; then
            echo "No tag points at HEAD, so we need a new tag and then a new release."
            echo "need_release=yes" >> "$GITHUB_OUTPUT"
          else
            RELEASE=$(gh release view "$TAG" --json tagName --jq '.tagName' || echo "none")
            if [ "$RELEASE" == "$TAG" ]; then
              echo "A release exists for tag $TAG, which has the latest changes, so no need for a new tag or release."
              echo "need_release=no" >> "$GITHUB_OUTPUT"
            else
              echo "Tag $TAG exists, but no release is associated. Need a new release."
              echo "need_release=yes" >> "$GITHUB_OUTPUT"
              echo "existing_tag=$TAG" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        if: steps.check.outputs.need_release == 'yes' && steps.check.outputs.existing_tag == ''
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: steps.check.outputs.need_release == 'yes'
        with:
          ref: ${{ steps.check.outputs.existing_tag || steps.create_tag.outputs.new_tag }}
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        if: steps.check.outputs.need_release == 'yes'
        with:
          go-version-file: './.go-version'
          check-latest: true
          cache: false

      - id: import_gpg
        if: steps.check.outputs.need_release == 'yes'
        uses: step-security/ghaction-import-gpg@c0b4a334b9b72bfaaebec86ef022a78a5b17f828 # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        if: steps.check.outputs.need_release == 'yes'
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
