name: Test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
        check-latest: true

    - name: Check out code
      uses: actions/checkout@v3

    - name: Linting (golangci-lint)
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - name: Compile
      run: |
        go build -v .

  test:
    name: 'Acceptance tests (OS: ${{ matrix.os }} / TF: ${{ matrix.terraform }})'
    needs: build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        terraform:
          - '0.12.*'
          - '0.13.*'
          - '0.14.*'
          - '0.15.*'
          - '1.0.*'
          - '1.1.*'
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
        check-latest: true

    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Terraform ${{ matrix.terraform }}
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false

    - name: Acceptance test
      env:
        TF_ACC: "1"
      run: |
        go test -v -cover ./...
